### ISSUE TITLE
not working with vue3

### ISSUE THREAD

**Issue by RHRiday** [hanhdt/vue-trix#382]
Displays the following error on `npm run dev` command

```
X [ERROR] No matching export in "node_modules/vue/dist/vue.runtime.esm-bundler.js" for import "default"

    node_modules/vue-trix/dist/vue-trix.esm.js:1:7:
      1 │ import Vue from 'vue';
        ╵        ~~~

E:\Web practice\resume-builder\node_modules\esbuild\lib\main.js:1566
  let error = new Error(`${text}${summary}`);
              ^

Error: Build failed with 1 error:
node_modules/vue-trix/dist/vue-trix.esm.js:1:7: ERROR: No matching export in "node_modules/vue/dist/vue.runtime.esm-bundler.js" for import "default"
    at failureErrorWithLog (E:\Web practice\resume-builder\node_modules\esbuild\lib\main.js:1566:15)
    at E:\Web practice\resume-builder\node_modules\esbuild\lib\main.js:1024:28
    at runOnEndCallbacks (E:\Web practice\resume-builder\node_modules\esbuild\lib\main.js:1438:61)
    at buildResponseToResult (E:\Web practice\resume-builder\node_modules\esbuild\lib\main.js:1022:7)
    at E:\Web practice\resume-builder\node_modules\esbuild\lib\main.js:1134:14
    at responseCallbacks.<computed> (E:\Web practice\resume-builder\node_modules\esbuild\lib\main.js:671:9)
    at handleIncomingPacket (E:\Web practice\resume-builder\node_modules\esbuild\lib\main.js:726:9)
    at Socket.readFromStdout (E:\Web practice\resume-builder\node_modules\esbuild\lib\main.js:647:7)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12) {
  errors: [
    {
      detail: undefined,
      id: '',
      location: {
        column: 7,
        file: 'node_modules/vue-trix/dist/vue-trix.esm.js',
        length: 3,
        line: 1,
        lineText: "import Vue from 'vue';",
        namespace: '',
        suggestion: ''
      },
      notes: [],
      pluginName: '',
      text: 'No matching export in "node_modules/vue/dist/vue.runtime.esm-bundler.js" for import "default"'
    }
  ],
  warnings: []
}
```

**Comment by ycrepeau** [comment]
Same error for me (6 months later)

**Comment by knubbe82** [comment]
Same error

**Comment by caspii** [comment]
Same error. Is this project dead?

**Comment by hanhdt** [comment]
@caspii Sorry, I have been busy recently so don't have time to take a look at the Vue3 support.
I believe that Vue3 has another mechanism for exporting the module.
